# Generated by Django 6.0 on 2025-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_role", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=100)),
                ("match_score", models.IntegerField()),
                ("matched_skills", models.JSONField()),
                ("missing_skills", models.JSONField()),
                ("suggestions", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
