# Generated by Django 6.0 on 2025-12-18 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resumeanalysis_alter_resume_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="resume",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="resume.resume",
            ),
            preserve_default=False,
        ),
    ]
