# Generated by Django 6.0 on 2025-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_resumeanalysis_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="detected_name",
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
    ]
